apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  schedule: {{ default "*/5 * * * *" .Values.schedule | quote }}
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 180
  suspend: false
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: {{ .Release.Name }}
            app: {{ .Release.Name }}
        spec:
          containers:
          - name: azure-ddns
            image: ghcr.io/pacroy/azure-ddns:v{{ .Chart.AppVersion }}
            imagePullPolicy: IfNotPresent
            env:
            - name: CLIENT_ID
              value: {{ required "clientId is not specified" .Values.clientId | quote }}
            - name: CLIENT_SECRET
              value: {{ required "clientSecret is not specified" .Values.clientSecret | quote }}
            - name: TENANT_ID
              value: {{ required "tenantId is not specified" .Values.tenantId | quote }}
            - name: RESOURCE_GROUP
              value: {{ required "resourceGroup is not specified" .Values.resourceGroup | quote }}
            - name: DNSZONE
              value: {{ required "dnsZone is not specified" .Values.dnsZone | quote }}
            - name: RECORD_NAMES
              value: {{ required "recordNames is not specified" .Values.recordNames | quote }}
            - name: UPDATE_IP_CMD
              value: {{ .Values.updateIpCommand | quote }}
          restartPolicy: Never
